# https://zenn.dev/chocoyama/articles/654a80f96d10ef

name-template: '🍏 $RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

tag-prefix: v

prerelease: true

template: |
  ## What’s Changed

  $CHANGES
