# https://zenn.dev/chocoyama/articles/654a80f96d10ef

name-template: '🍏 v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: minor

tag-prefix: v

prerelease: true
prerelease-identifier: dev

template: |
  ## What’s Changed

  $CHANGES
