name: Create release notes

on:
  workflow_dispatch:
    inputs:
      commit-ish:
        type: string
        required: true
        description: 'ビルド対象'
        default: main

permissions:
  contents: read

jobs:
  update_releases:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit-ish }}
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Detect app version from manifest
        id: detect_version
        env:
          GRADLE_TASK: ":app:processDebugMainManifest" # assembleDebug # ":app:processDebugMainManifest"
          MANIFEST_FILE: ./app/build/intermediates/merged_manifest/debug/processDebugMainManifest/AndroidManifest.xml
        run: |
          ./gradlew $GRADLE_TASK
          cat "$MANIFEST_FILE" | python3 tools/apk_util/parse_app_version.py >> "$GITHUB_OUTPUT"
          TZ=Asia/Tokyo date "+%Y%m%dT%H%M%S" | xargs -I"{}" echo "dev_version={}" >> "$GITHUB_OUTPUT"

      - name: Create release notes
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git_tag="v${{ steps.detect_version.outputs.version_name }}(${{ steps.detect_version.outputs.version_code }}).dev.${{ steps.detect_version.outputs.dev_version }}"
          gh release create "$git_tag" --generate-notes --draft --prerelease --target ${{ github.event.inputs.commit-ish }}
